globals:
  # Path to the ocio config to use
  ocioconfig: ocio://studio-config-v1.0.0_aces-v1.3_ocio-v2.1

  # Default ocio profile to use if not specified on the commandline
  ocio_default_transform: grade

  ###############################################
  ## Reformatting and Cropping
  ###############################################
  # If debug is true, no encoding will be done and there will be debug prints
  debug: true
  # Number of pixels to crop from width and height before resizing to dailies res.
  # Enter an int pixel number, or a percentage like  5% or 6.25%
  cropwidth:
  cropheight:
  # width and height are the resolution to reformat to.
  width: 1920
  height: 1080
  # If fit=false there will be no padding: height will be ignored and the aspect ratio of the input will be preserved.
  fit: true

  # Enable an oiio pixel filter to use for scaling. Default is good: blackman-harris for scaling up, lanczos3 for scaling down.
  #
  # Possible filters: https://github.com/OpenImageIO/oiio/blob/master/src/libutil/filter.cpp
  #     // name              dim width fixedwidth scalable separable
  #     { "box",             1,   1,    false,    true,     true },
  #     { "triangle",        1,   2,    false,    true,     true },
  #     { "gaussian",        1,   3,    false,    true,     true },
  #     { "sharp-gaussian",  1,   2,    false,    true,     true },
  #     { "catmull-rom",     1,   4,    false,    true,     true },
  #     { "blackman-harris", 1,   3,    false,    true,     true },
  #     { "sinc",            1,   4,    false,    true,     true },
  #     { "lanczos3",        1,   6,    false,    true,     true },
  #     { "mitchell",        1,   4,    false,    true,     true },
  #     { "bspline",         1,   4,    false,    true,     true },
  #     { "cubic",           1,   4,    false,    true,     true },
  #     { "keys",            1,   4,    false,    true,     true },
  #     { "simon",           1,   4,    false,    true,     true },
  #     { "rifman",          1,   4,    false,    true,     true }
  filter: box

  # Output framerate. film=24, hdtv=23.98 = 24000/1001, pal=25, ntsc=30000/1001
  #framerate: 30000/1001
  framerate: 30

  # specify a default video filter string to use in ffmpeg.
  # https://trac.ffmpeg.org/wiki/Scaling
  # https://ffmpeg.org/ffmpeg-scaler.html
  # Example: "lut3d=${lut},scale=w=${width}:h=${height}:force_original_aspect_ratio=1,pad=${width}:${height}:(ow-iw)/2:(oh-ih)/2"
  vf:
  # Choose which output profile to use by default if none specified. See options below.
  output_codec: h264_hq
  # Movie location is a relative or absolute path for where to place the daily movie
  # For example ../ will place it in the directory above the frames. /place/output will place it here.
  movie_location: ~/tmp/dailies
  movie_ext: mov
  # If true, appends "_<codec name>" to the movie file
  movie_append_codec: true
  # All possible input image extensions that will be considered. (Uppercase will automatically be added)
  input_image_formats: ['exr', 'tif', 'tiff', 'png', 'jpg', 'jpeg', 'iff', 'tex', 'tx', 'jp2', 'j2c']


###############################################
## OpenColorIO Profiles
###############################################

ocio_profiles:
  #TODO: tweak
  grade:
    # ocio colorspace conversion: [src_colorspace, dst_colorspace]
    ociocolorconvert: ["scene_linear", "client_grade"]
  show_log:
    ociocolorconvert: ["scene_linear", "color_timing"]
  acescg2srgb:
    ociocolorconvert: ["ACEScg", "Output - sRGB"]
  logc2srgb:
    ociocolorconvert: ["Input - ARRI - V3 LogC (EI800) - Wide Gamut", "Output - sRGB"]
  logc2acescg:
    ociocolorconvert: ["Input - ARRI - V3 LogC (EI800) - Wide Gamut", "ACES - ACEScg"]

###############################################
## Dailies Overlay Profiles
###############################################


# Dailies overlay profiles to use for different purposes. Each profile allows you to specify an overlay behavior.
dailies_profiles:
  # Internal Daily: overlays for frame counter, artist, comment, date, etc
  internal:
    # path to ttf font file
    font:
    # Specify default font size in percentage of frame width. E.g. a value of 1.0 in a 1920x1080 image would be 19.6px
    # small = 0.4, medium = 0.8, big = 1.3
    font_size:
    # justify x left or center
    justify:
    # Specify the percentage of font_size to use as leading: the space between lines
    leading: 0.15
    # Specify default font color [R,G,B,A]
    font_color: [0.8, 0.8, 0.8, 1.0]

    # Enable an overlay to crop the pixels to a specific aspect ratio.
    # For example to do a hard crop to 2.35 set the cropmask-ar to 2.35 and the crop mask opacity to 1.0
    cropmask:
      enable: true
      aspect: 2.39
      opacity: 0.75

    text_elements:
      date:
        enable: true
        prefix:
        font: fonts/Helvetica/Helvetica.ttf
        font_size: 0.015
        font_color: [0.8, 0.8, 0.8, 1.0]
        datetime_format: "%Y-%m-%d"
        anchor: [.98, .02]
        hjustify: right
        vjustify: top

      artist:
        enable: true
        prefix:
        font: fonts/Helvetica/Helvetica.ttf
        font_size: 0.015
        font_color: [0.8, 0.8, 0.8, 1.0]
        anchor: [.5, .02]
        hjustify: center
        vjustify: top

      sequence:
        enable: true
        prefix:
        font: fonts/Helvetica/Helvetica.ttf
        font_size: 0.015
        font_color: [0.8, 0.8, 0.8, 1.0]
        anchor: [.02, .02]
        hjustify: left
        vjustify: top

      comment:
        enable: true
        prefix:
        font: fonts/Helvetica/Helvetica.ttf
        font_size: 0.015
        font_color: [0.8, 0.8, 0.8, 1.0]
        anchor: [.02, .98]
        hjustify: left
        vjustify: bottom


      framecounter:
        enable: true
        prefix:
        font: fonts/Helvetica/Helvetica.ttf
        font_size: 0.015
        font_color: [0.8, 0.8, 0.8, 1.0]
        padding: 5
        anchor: [.98, .98]
        hjustify: right
        vjustify: bottom

      discipline:
        enable: true
        prefix:
        font: fonts/Helvetica/Helvetica.ttf
        font_size: 0.015
        font_color: [0.8, 0.8, 0.8, 1.0]
        anchor: [.01, .01]
        hjustify: center
        vjustify: center


  # Delivery profile - minimal overlays with cropmask and slate.
  delivery:
    cropmask:
    framecounter:
    slate:
    text_elements:

# Output profile definitions.
output_codecs:
  avchq:
    name: avchq
    overlay: internal_daily
    cropwidth:
    cropheight:
    width: 1920
    height: 1080
    fit:
    framerate:
    codec: libx264
    profile: high444
    qscale:
    preset: slower
    keyint: 1
    bframes: 0
    tune: film
    crf: 13
    pix_fmt: yuv444p10le
    vf: colormatrix=bt601:bt709
    bitdepth: 10
    vendor:
    metadata_s:
    bitrate:
    movie_ext: mov

  avclq:
    name: avclq
    overlay: internal_daily
    cropwidth:
    cropheight:
    width:
    height:
    fit:
    framerate:
    codec: libx264
    profile: high
    qscale:
    preset: slower
    keyint: 1
    bframes: 0
    tune: film
    crf: 17
    pix_fmt: yuv420p
    vf: colormatrix=bt601:bt709
    bitdepth: 8
    vendor:
    metadata_s:
    bitrate:
    movie_ext: mp4

  avc_lq:
    name: avc_lq
    overlay: internal_daily
    cropwidth:
    cropheight:
    width:
    height:
    fit:
    framerate:
    codec: libx264
    profile: high444
    qscale:
    preset: slower
    keyint: 1
    bframes: 0
    tune: film
    crf: 17
    pix_fmt: yuv444p10le
    vf: colormatrix=bt601:bt709
    bitdepth: 8
    vendor:
    metadata_s:
    bitrate:
    movie_ext: mov

  avcth:
    name: avcth
    overlay: internal_daily
    cropwidth:
    cropheight:
    width:
    height:
    fit:
    framerate:
    codec: libx264
    profile: high
    qscale:
    preset: faster
    keyint: 1
    bframes: 0
    tune: film
    crf: 22
    pix_fmt: yuv420p
    vf: colormatrix=bt601:bt709
    bitdepth: 8
    vendor:
    metadata_s:
    bitrate:
    movie_ext: mp4


  ##############################################################
  # x265: https://x265.readthedocs.io/en/default/cli.html
  # The following profiles are supported in x265.
  # 8bit profiles:
  # * main, main-intra, mainstillpicture (or msp for short)
  # * main444-8, main444-intra, main444-stillpicture
  # 10bit profiles:
  # * main10, main10-intra
  # * main422-10, main422-10-intra
  # * main444-10, main444-10-intra
  # 12bit profiles:
  # * main12, main12-intra
  # * main422-12, main422-12-intra
  # * main444-12, main444-12-intra

  hevc_hq:
    # https://unix.stackexchange.com/questions/230800/re-encoding-video-library-in-x265-hevc-with-no-quality-loss
    # https://gist.github.com/Brainiarc7/8b471ff91319483cdb725f615908286e
    name: hevc_hq
    overlay: internal_daily
    cropwidth:
    cropheight:
    width: 1920
    height: 1080
    fit:
    framerate:
    codec: libx265
    profile: main444-10-intra
    qscale:
    # Possible presets: ultrafast superfast veryfast faster fast medium slow slower veryslow placebo
    preset: medium
    keyint: 1
    bframes: 0
    # Possible tunes: psnr ssim grain zerolatency fastdecode
    tune: psnr
    crf: 13
    pix_fmt: yuv444p10le
    vf: colormatrix=bt601:bt709
    bitdepth: 10
    vendor:
    metadata_s:
    bitrate:
    movie_ext: mov

  hevc_lq:
    name: hevc_lq
    overlay: internal_daily
    cropwidth:
    cropheight:
    width: 1920
    height: 1080
    fit:
    framerate:
    codec: libx265
    profile: main10-intra
    qscale:
    # Possible presets: ultrafast superfast veryfast faster fast medium slow slower veryslow placebo
    preset: medium
    keyint: 1
    bframes: 0
    # Possible tunes: psnr ssim grain zerolatency fastdecode
    tune: psnr
    crf: 17
    pix_fmt: yuv420p10le
    vf: colormatrix=bt601:bt709
    bitdepth: 10
    vendor:
    metadata_s:
    bitrate:
    movie_ext: mov

  hevc:
    name: hevc
    overlay: internal_daily
    cropwidth:
    cropheight:
    width: 1920
    height: 1080
    fit:
    framerate:
    codec: libx265
    profile: main10
    qscale:
    # Possible presets: ultrafast superfast veryfast faster fast medium slow slower veryslow placebo
    preset: medium
    keyint:
    bframes:
    # Possible tunes: psnr ssim grain zerolatency fastdecode
    tune: psnr
    crf: 21
    pix_fmt: yuv420p10le
    vf: colormatrix=bt601:bt709
    bitdepth: 10
    vendor:
    metadata_s:
    bitrate:
    movie_ext: mov

  prores_4444:
    name: prores_4444
    overlay: delivery
    width:
    height:
    fit:
    framerate:
    codec: prores_ks
    profile: 4
    qscale: 5
    preset:
    keyint:
    bframes:
    tune:
    crf:
    pix_fmt: yuva444p10le
    vf: colormatrix=bt601:bt709
    bitdepth: 10
    vendor: ap10
    metadata_s: encoder="Apple ProRes 4444"
    bitrate:
    movie_ext: mov

  prores_422hq:
    name: prores_422hq
    overlay: delivery
    width:
    height:
    fit:
    framerate:
    codec: prores_ks
    profile: 3
    qscale: 7
    preset:
    keyint:
    bframes:
    tune:
    crf:
    pix_fmt: yuva444p10le
    vf: colormatrix=bt601:bt709
    bitdepth: 10
    vendor: ap10
    metadata_s: encoder="Apple ProRes 422 HQ"
    bitrate:
    movie_ext: mov

  prores_422:
    name: prores_422
    overlay: delivery
    width:
    height:
    fit:
    framerate:
    codec: prores_ks
    profile: 2
    qscale: 7
    preset:
    keyint:
    bframes:
    tune:
    crf:
    pix_fmt: yuva444p10le
    vf: colormatrix=bt601:bt709
    bitdepth: 10
    vendor: ap10
    metadata_s: encoder="Apple ProRes 422 HQ"
    bitrate:
    movie_ext: mov

  dnxhd_36:
    overlay: delivery

  dnxhd_175:
    # http://forum.selur.de/topic1348-dnxhr-encoding.html
    # 1920x1080p  175 10  24000/1001
    name: dnxhd_175
    overlay: delivery
    width: 1920
    height: 1080
    fit: yes
    framerate: 24000/1001
    codec: dnxhd
    profile: dnxhd
    qscale:
    preset:
    keyint:
    bframes:
    tune:
    crf:
    pix_fmt: yuva422p10le
    vf: colormatrix=bt601:bt709
    bitdepth: 10
    vendor:
    metadata_s:
    bitrate: 175M
    movie_ext: mov

  dnxhr_hqx:
    # https://askubuntu.com/questions/907398/how-to-convert-a-video-with-ffmpeg-into-the-dnxhd-dnxhr-format
    # dnxhd, dnxhr_444, dnxhr_hqx, dnxhr_hq, dnxhr_sq, dnxhr_lb
    # 12 bit 4:2:2
    name: dnxhr_hqx
    width:
    height:
    fit:
    framerate:
    codec: dnxhd
    profile: dnxhr_hqx
    qscale:
    preset:
    keyint:
    bframes:
    tune:
    crf:
    pix_fmt: yuv422p12le
    vf: colormatrix=bt601:bt709
    bitdepth: 12
    vendor:
    metadata_s:
    bitrate: 175M
    movie_ext: mov

  mjpeg:
    # Special codec to concatenate input images into a quicktime container
    name: mjpeg
    overlay: internal_daily
    cropwidth:
    cropheight:
    width: 1920
    height: 1080
    fit:
    framerate:
    codec: copy
    profile:
    # Jpeg compression quality: 0-100
    quality: 90
    qscale:
    preset:
    keyint:
    bframes:
    tune:
    crf:
    pix_fmt:
    vf:
    bitdepth: 8
    vendor:
    metadata_s:
    bitrate:
    movie_ext: mov
